swagger: '2.0'
info:
  title: Access Backend API
  version: 1.0.0

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "JWT Authorization header using the Bearer scheme. Example: 'Bearer {token}'"

security:
  - Bearer: []

paths:
  /auth/login:
    post:
      summary: Login to get JWT token
      tags:
        - Auth
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: JWT token returned
        '401':
          description: Unauthorized

  /auth/logout_access:
    post:
      summary: Logout (revoke access token)
      tags:
        - Auth
      security:
        - Bearer: []
      responses:
        '200':
          description: Logged out

  /auth/me:
    get:
      summary: Get current user info
      tags:
        - Auth
      security:
        - Bearer: []
      responses:
        '200':
          description: User info returned
        '401':
          description: Unauthorized or invalid token
        '404':
          description: User not found

  /auth/refresh:
    post:
      summary: Refresh JWT token
      tags:
        - Auth
      security:
        - Bearer: []
      responses:
        '200':
          description: New token

  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            required:
              - username
              - email
              - password
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        '201':
          description: User successfully registered
        '400':
          description: Bad request, e.g., user exists or invalid data
